site_name: route53-dynamic-dns
site_description: Update AWS Route53 hosted zone with current public IP address. Alternative to Dynamic DNS services such as Dyn, No-IP, etc
site_author: sjmayotte
site_url: https://sjmayotte.dev/route53-dynamic-dns/
edit_uri: edit/master/docs/
docs_dir: docs

repo_name: sjmayotte/route53-dynamic-dns
repo_url: https://github.com/sjmayotte/route53-dynamic-dns

extra:
  social:
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/sjmayotte/route53-dynamic-dns/
    - icon: fontawesome/brands/github
      link: https://github.com/sjmayotte
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/stevemayotte
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/SteveMayotte
  analytics:
    provider: google
    property: G-RPGNP3RWVE
  #seo:
    #google:
    #bing:

theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - git-revision-date-localized:
      type: iso_datetime
      enable_creation_date: true

nav:
  - Home: index.md
  - Installation:
    - Docker: install/docker.md
    - Node Process: install/node.md
    - Kubernetes: install/kubernetes.md
  - Usage:
    - Docker: usage/docker.md
    - Node Process: usage/node.md
    - Logs: usage/logs.md
  - Configuration:
    - Environment Variables: config/env.md
    - AWS Services: config/aws.md
  - FAQ: faq.md
  - Reporting an issue: issues.md
  - Contributing: contributing.md
